### ISSUE TITLE
'About Eclipse SDK' dialog has duplicate icons, can this be merged into 1 icon showing full list

### ISSUE THREAD

**Issue by deepika-u** [eclipse-platform/eclipse.platform#2261]
Description
When i open the "About Eclipse SDK" -> Help menu, i see the below dialog

<img width="688" height="606" alt="Image" src="https://github.com/user-attachments/assets/7d98daf0-20cd-4d8c-be3b-6d996c3bec9a" />

The first 2 icons both show the same tooltip as "Eclipse.org". 

1.  When i click on the 1st Icon(not so good looking among both) i see below features listed like SDK, RCP, JDT, Platform, Help.

<img width="873" height="990" alt="Image" src="https://github.com/user-attachments/assets/243a0e62-38ca-4a1d-a4cb-c213bf3d5127" />

2. When i click on the 2nd Icon(good looking icon) i see PDE feature and its details in the similar lines.

<img width="871" height="988" alt="Image" src="https://github.com/user-attachments/assets/780a48bf-f0e7-4e77-b691-fbaa515dae66" />

Can we we have 2nd one good looking icon and have all the list populated in it?
Is this expected behavior or can this be merged into 1 entry?
I see this behavior on Windows 11 and on below build ```
Version: 2025-12 (4.38)
Build id: I20251108-1800
```

**Comment by deepika-u** [comment]
I just tried on 4.32 and see as below

<img width="582" height="530" alt="Image" src="https://github.com/user-attachments/assets/00c79d3a-035f-4ece-800f-fa96f4c8a4d8" />

and when clicked on 1st icon i see as below

<img width="1127" height="914" alt="Image" src="https://github.com/user-attachments/assets/ebe819f1-1d48-4b23-b7fe-d823f787f166" />

I see all the features and their versions listed here. I also see 1 other "Eclipse User Storage" here.

**Comment by iloveeclipse** [comment]
@merks, @laeubi, @HannesWell : any idea why PDE entry is separated now? Some magic p2 instructions missing / too much / wrong? What I also observe, the icon for PDE is different - is **that** the root cause?

**Comment by laeubi** [comment]
Last time I looked into this it is dependent on the branding plugin used for a feature, that is offering the icon and the about text.

**Comment by merks** [comment]
Yes, it's on my TODO list to figure out why these two are not merged.   I'll try to get to this as soon as possible; this is not yet at the top of the queue, but getting there...

**Comment by laeubi** [comment]
Just a guess from my side, PDE has updates in it feature and uses a new branding plugin version while the other feature where not updated in a while and using an old one. So touching the features will likely resolve the issue.

**Comment by merks** [comment]
Yes, I need to look at implementation details, but I would assume (and hope) that if two different branding plugins have different images that they will not be merged.  Here are all the places that define or process the `featureImage` property:

<img width="606" height="1881" alt="Image" src="https://github.com/user-attachments/assets/a152e295-67c3-4dd6-9c45-a5aac3364de2" />

Mostly the definitions all use `*.png` except for pde and the test tools.  So, probably moving forward we want all these to use the same `*.svg`, right?  (As opposed to reverting PDE's change.)

**Comment by merks** [comment]
FYI, we'll need to check the I-build to verify that the problem is fixed by the changes.

**Comment by deepika-u** [comment]
@merks  I just tried on `Version: 2025-12 (4.38) Build id: I20251111-1800`

I still see 2 icons

<img width="674" height="589" alt="Image" src="https://github.com/user-attachments/assets/442817be-6c7e-4561-a2f3-8faaa9ed0ed8" />

<img width="681" height="600" alt="Image" src="https://github.com/user-attachments/assets/283839e5-3a5e-4bd1-bd4b-d46134368bbd" />

When clicked on 1st icon
<img width="878" height="719" alt="Image" src="https://github.com/user-attachments/assets/23679405-3859-4c58-89cc-5c5579f4d5b1" />

When clicked on 2nd icon
<img width="864" height="596" alt="Image" src="https://github.com/user-attachments/assets/5e3862b6-c98c-4eb7-9f5a-bc4c178b7580" />

So features are jumbled here and there but issue still persists. Was this "org.eclipse.userstorage" feature intentionally removed? or it is missing?(since we see this in 4.32).

**Comment by merks** [comment]
So more of them group with PDE now; that's good and expected.  The other two projects (from the second icon) already had existing eclipse32.svg in their folder. (While checking if they're the same I found that opening two *.svg deadlocks the IDE.  I'll open an issue for that.) 

Comparing the two I see they are different as suggested by the grouping behavior:

<img width="1422" height="695" alt="Image" src="https://github.com/user-attachments/assets/6e4beae4-56df-41ae-9475-a9ef2c0cd043" />

So that would explain it.

Those two folders are full of icons so probably best I copy the one from there to the other projects, including to PDE so that they are uniformly the same across the branding plugins:

<img width="388" height="907" alt="Image" src="https://github.com/user-attachments/assets/f771fca4-89a4-4d54-b5c4-ea59dbeb305d" />

---

Why are you asking about org.eclipse.userstorage from this archived project?

https://projects.eclipse.org/projects/technology.usssdk

**Comment by laeubi** [comment]
>  PDE so that they are uniformly the same across the branding plugins

If we really want to have uniform results, should we maybe have *one* `org.eclipse.platform.branding` plugin to be used in all features like we do for the licensing feature?

**Comment by merks** [comment]
I really prefer not to turn this small glitch into a "let's redesign the branding plug-plugin infrastructure".    I think we all have more important things to do; things that will have more value for our users.

**Comment by deepika-u** [comment]
> Why are you asking about org.eclipse.userstorage from this archived project?
> 
> https://projects.eclipse.org/projects/technology.usssdk

So it means this is expected and done intentionally. Thanks for confirming on that.

**Comment by merks** [comment]
The images should all be consistently the same now.  I copied one to all locations.

<img width="449" height="36" alt="Image" src="https://github.com/user-attachments/assets/5873c3ac-173a-4e3d-b8a6-4f3dddf16ea1" />

We'll see after the next I-build...

**Comment by deepika-u** [comment]
This is on `Version: 2025-12 (4.38) Build id: I20251112-1800`. Now i see single icon as below

<img width="685" height="606" alt="Image" src="https://github.com/user-attachments/assets/f658131c-79bc-4d0d-941e-e7712623efef" />

Upon opening that icon i see as below

<img width="869" height="708" alt="Image" src="https://github.com/user-attachments/assets/ec60962e-3aaa-4fd8-9fb9-f69a411117ea" />

Thanks @merks  for the quick look into it.

**Comment by iloveeclipse** [comment]
Thanks @merks ! Closing as fixed.
